services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8501:8501
    env_file:
      - .env_streamlit
    restart: unless-stopped
    volumes:
      - ./src/chatbot_ui:/app/src/chatbot_ui
  api:
    build:
        context: .
        dockerfile: Dockerfile.fastapi
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - .env_api
    restart: unless-stopped
    volumes:
      - ./src/api:/app/src/api
      - ./log/api:/app/logs

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped
